"""Add name and role to User model

Revision ID: 9dca5ba072cc
Revises: 4afae26fe1bd
Create Date: 2025-06-21 10:01:37.920196

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9dca5ba072cc'
down_revision = '4afae26fe1bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed: op.drop_table('spatial_ref_sys') - Ne pas supprimer cette table système PostGIS
    
    op.add_column('incidents', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('state', sa.String(length=50), nullable=False, server_default='pending_validation'))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # Try to drop index if it exists
    try:
        op.drop_index(op.f('idx_user_email'), table_name='users')
    except:
        pass  # Skip if index doesn't exist
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    try:
        op.create_index(op.f('idx_user_email'), 'users', ['email'], unique=True)
    except:
        pass  # Skip if index can't be created
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'name')
    op.drop_column('incidents', 'state')
    op.drop_column('incidents', 'image_url')
    # Ne pas recréer la table spatial_ref_sys
    # ### end Alembic commands ###
