name: green_sentinel_mobile
description: GreenSentinel citizen mobile app for environmental reporting
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  formz: ^0.6.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  dio: ^5.4.2
  connectivity_plus: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  workmanager: ^0.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - ../design-tokens.json
