server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    
    # Extract Docker container information
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            source: attrs.source
            image: attrs.container_name
            container_id: attrs.container_id
            
      - regex:
          expression: (?P<container_name>.*)-(?P<container_id>[a-z0-9]{64})\.log
          source: filename
          
      - labels:
          stream:
          container_name:
          container_id: 
          
      # Ensure proper timestamps
      - timestamp:
          source: time
          format: RFC3339Nano
          
      # Clean up log content
      - output:
          source: message
