name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: salaheddineelazouti/greensentinel
    
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          salaheddineelazouti/greensentinel-backend:${{ github.ref_name }}
          salaheddineelazouti/greensentinel-backend:latest
    
    - name: Build and push vision service image
      uses: docker/build-push-action@v5
      with:
        context: ./vision_service
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          salaheddineelazouti/greensentinel-vision:${{ github.ref_name }}
          salaheddineelazouti/greensentinel-vision:latest
    
    - name: Build and push worker service image
      uses: docker/build-push-action@v5
      with:
        context: ./backend/worker_service
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          salaheddineelazouti/greensentinel-worker:${{ github.ref_name }}
          salaheddineelazouti/greensentinel-worker:latest
    
    - name: Build and push admin app image
      uses: docker/build-push-action@v5
      with:
        context: ./admin-app
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          salaheddineelazouti/greensentinel-admin:${{ github.ref_name }}
          salaheddineelazouti/greensentinel-admin:latest
    
    - name: Build and push pro app image
      uses: docker/build-push-action@v5
      with:
        context: ./pro-app
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          salaheddineelazouti/greensentinel-pro:${{ github.ref_name }}
          salaheddineelazouti/greensentinel-pro:latest
